# Generated by Django 2.2 on 2020-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnn', models.CharField(blank=True, max_length=80)),
                ('torgName', models.CharField(max_length=100)),
                ('lekForm', models.CharField(blank=True, max_length=250)),
                ('factory', models.CharField(blank=True, max_length=250)),
                ('ATX', models.CharField(blank=True, max_length=20)),
                ('count', models.CharField(blank=True, max_length=20)),
                ('predCena', models.CharField(max_length=50)),
                ('CenaPervUpak', models.CharField(blank=True, max_length=50)),
                ('ru', models.CharField(blank=True, max_length=30)),
                ('dateReg', models.CharField(blank=True, max_length=80)),
                ('EAN13', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
