# Generated by Django 2.2 on 2020-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leki',
            name='predCena',
            field=models.FloatField(),
        ),
    ]
